// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5ZY_k-Y-hrr1bKJcUxBtrs1zo-4vPz0',
    appId: '1:970668995057:web:1c798c9ba2066696da9450',
    messagingSenderId: '970668995057',
    projectId: 'my-flutter-training-efb19',
    authDomain: 'my-flutter-training-efb19.firebaseapp.com',
    storageBucket: 'my-flutter-training-efb19.appspot.com',
    measurementId: 'G-PV9N6RV4W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD00d1qD0OoIaw3uTxQUcfD0vh078mrt4',
    appId: '1:970668995057:android:88cf7fec4c1b1446da9450',
    messagingSenderId: '970668995057',
    projectId: 'my-flutter-training-efb19',
    storageBucket: 'my-flutter-training-efb19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03LiUt05ui_6Tu1sz5zM4zSUbhpd6SJA',
    appId: '1:970668995057:ios:6ace58723671f57dda9450',
    messagingSenderId: '970668995057',
    projectId: 'my-flutter-training-efb19',
    storageBucket: 'my-flutter-training-efb19.appspot.com',
    iosBundleId: 'com.example.myflutterTrainingTask',
  );
}
